sudo: true
language: generic

notifications:
  email: false

os:
  - linux
  - osx

cache:
  directories:
  - $HOME/.stack
  - $TRAVIS_BUILD_DIR/.stack-work

env:
  global:
    - GITHUB_RELEASE_VERSION=1.2.4

before_install:
  - mkdir -p ~/.local/bin
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        travis_retry curl -sSL https://www.stackage.org/stack/osx-x86_64   | tar xz --strip-components=1 --include  '*/stack' -C ~/.local/bin
    else
        travis_retry curl -sSL https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi

install:
  - stack setup --no-terminal
  - stack build --only-dependencies --test --copy-bins

script:
  - stack test --copy-bins
